version: '3'
services:
  postgresql:
    image: 'postgres'
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  springboot:
    container_name: springboot
    image: spring
    build: ./online-city-tickets-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  angular:
    restart: always
    container_name: angular
    image: angular
    build: ./online-city-tickets-frontend
    ports:
      - "8000:80"
      - "443:443"
    stdin_open: true
    volumes:
      - ./ssl:/etc/nginx/certs
    depends_on:
      - springboot
