on:
  push:
    paths:
      - online-city-tickets-backend/**
      - .github/workflows/backend.yml
      - compose.yml

jobs:
  spring-boot:
    name: Build and test project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: online-city-tickets-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: Check formatting
        run: ./gradlew spotlessCheck

      - name: Run Build
        run: ./gradlew assemble

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Integration Tests
        run: ./gradlew integrationTest
